// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"context"
)

type Querier interface {
	CreateAuthor(ctx context.Context, arg CreateAuthorParams) (Author, error)
	CreateRecipe(ctx context.Context, arg CreateRecipeParams) (Recipe, error)
	DeleteAuthor(ctx context.Context, username string) error
	DeleteRecipe(ctx context.Context, id int64) error
	GetAuthor(ctx context.Context, username string) (Author, error)
	GetRecipe(ctx context.Context, id int64) (Recipe, error)
	ListAuthors(ctx context.Context, arg ListAuthorsParams) ([]Author, error)
	ListRecipes(ctx context.Context, arg ListRecipesParams) ([]Recipe, error)
	UpdateAuthor(ctx context.Context, arg UpdateAuthorParams) (Author, error)
	UpdateRecipe(ctx context.Context, arg UpdateRecipeParams) (Recipe, error)
}

var _ Querier = (*Queries)(nil)
